services:
  db:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: springboot_app
    env_file:
      - .env.dev
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
